version: 2
updates:
  # Production dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    target-branch: 'develop'
    labels:
      - 'dependencies'
      - 'automated'
    reviewers:
      - 'ThomasHeim11'
    open-pull-requests-limit: 5

  # Security updates (more frequent)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    labels:
      - 'security'
      - 'dependencies'
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: 'develop'
    labels:
      - 'github-actions'
      - 'dependencies'

  # Docker (if using containers)
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 3
    reviewers:
      - 'thomasheim'
    commit-message:
      prefix: 'docker'
      include: 'scope'
    labels:
      - 'docker'
      - 'auto-update'
