[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://embed.typeform.com https://*.typeform.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://api.typeform.com https://*.typeform.com;
      frame-src 'self' https://embed.typeform.com https://*.typeform.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://form.typeform.com;
      frame-ancestors 'none';
      upgrade-insecure-requests;
      block-all-mixed-content;
    '''
    
    # HTTP Strict Transport Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions Policy
    Permissions-Policy = '''
      camera=(),
      microphone=(),
      geolocation=(),
      payment=(),
      usb=(),
      magnetometer=(),
      gyroscope=(),
      accelerometer=(),
      autoplay=(),
      encrypted-media=(),
      fullscreen=(),
      picture-in-picture=()
    '''
    
    # Cross-Origin Policies
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    
    # Cache Control for security
    Cache-Control = "public, max-age=31536000, immutable"

# Special headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers for API endpoints (if any)
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-store, no-cache, must-revalidate"

# Security.txt specific headers
[[headers]]
  for = "/.well-known/security.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400"

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://cypherpunksecurity.io/*"
  to = "https://cypherpunksecurity.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.cypherpunksecurity.io/*"
  to = "https://cypherpunksecurity.io/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.cypherpunksecurity.io/*"
  to = "https://cypherpunksecurity.io/:splat"
  status = 301
  force = true

# Security redirects - block common attack paths
[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/wp-admin/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/wp-login.php"
  to = "/404"
  status = 404

[[redirects]]
  from = "/admin/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/phpmyadmin/*"
  to = "/404"
  status = 404

# Rate limiting and DDoS protection (Netlify Pro feature)
# [[edge_functions]]
#   function = "rate-limit"
#   path = "/*"

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 